//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlijentApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PrevodSrb {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrevodSrb() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KlijentApp.PrevodSrb", typeof(PrevodSrb).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivan.
        /// </summary>
        public static string Aktivan {
            get {
                return ResourceManager.GetString("Aktivan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ažurirano.
        /// </summary>
        public static string Ažurirano {
            get {
                return ResourceManager.GetString("Ažurirano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.T.D. - Izlaz.
        /// </summary>
        public static string B_T_D____Izlaz {
            get {
                return ResourceManager.GetString("B_T_D____Izlaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.T.D. - Ulaz.
        /// </summary>
        public static string B_T_D____Ulaz {
            get {
                return ResourceManager.GetString("B_T_D____Ulaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brisanje.
        /// </summary>
        public static string Brisanje {
            get {
                return ResourceManager.GetString("Brisanje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj tipova dokumenata.
        /// </summary>
        public static string Broj_tipova_dokumenata {
            get {
                return ResourceManager.GetString("Broj_tipova_dokumenata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da.
        /// </summary>
        public static string Da {
            get {
                return ResourceManager.GetString("Da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite da ovo obrišete?.
        /// </summary>
        public static string Da_li_ste_sigurni_da_želite_da_ovo_obrišete_ {
            get {
                return ResourceManager.GetString("Da_li_ste_sigurni_da_želite_da_ovo_obrišete_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum transakcije.
        /// </summary>
        public static string Datum_transakcije {
            get {
                return ResourceManager.GetString("Datum_transakcije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji.
        /// </summary>
        public static string Detalji {
            get {
                return ResourceManager.GetString("Detalji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drugi formati - Izlaz.
        /// </summary>
        public static string Drugi_formati___Izlaz {
            get {
                return ResourceManager.GetString("Drugi_formati___Izlaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drugi formati - Ulaz.
        /// </summary>
        public static string Drugi_formati___Ulaz {
            get {
                return ResourceManager.GetString("Drugi_formati___Ulaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter aktivnih.
        /// </summary>
        public static string Filter_aktivnih {
            get {
                return ResourceManager.GetString("Filter_aktivnih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter izlaz.
        /// </summary>
        public static string Filter_izlaz {
            get {
                return ResourceManager.GetString("Filter_izlaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        public static string Filter_Opis {
            get {
                return ResourceManager.GetString("Filter_Opis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter opisa.
        /// </summary>
        public static string Filter_opisa {
            get {
                return ResourceManager.GetString("Filter_opisa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter pdf.
        /// </summary>
        public static string Filter_pdf {
            get {
                return ResourceManager.GetString("Filter_pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter tipa.
        /// </summary>
        public static string Filter_tipa {
            get {
                return ResourceManager.GetString("Filter_tipa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter ulaz.
        /// </summary>
        public static string Filter_ulaz {
            get {
                return ResourceManager.GetString("Filter_ulaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter xml.
        /// </summary>
        public static string Filter_xml {
            get {
                return ResourceManager.GetString("Filter_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma.
        /// </summary>
        public static string Firma {
            get {
                return ResourceManager.GetString("Firma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greška.
        /// </summary>
        public static string Greška {
            get {
                return ResourceManager.GetString("Greška", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to i/ili.
        /// </summary>
        public static string i_ili {
            get {
                return ResourceManager.GetString("i_ili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izlaz.
        /// </summary>
        public static string Izlaz {
            get {
                return ResourceManager.GetString("Izlaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmeni.
        /// </summary>
        public static string Izmeni {
            get {
                return ResourceManager.GetString("Izmeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iznos.
        /// </summary>
        public static string Iznos {
            get {
                return ResourceManager.GetString("Iznos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klijent.
        /// </summary>
        public static string Klijent {
            get {
                return ResourceManager.GetString("Klijent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klijenti.
        /// </summary>
        public static string Klijenti {
            get {
                return ResourceManager.GetString("Klijenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komentar.
        /// </summary>
        public static string Komentar {
            get {
                return ResourceManager.GetString("Komentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string Kontakt {
            get {
                return ResourceManager.GetString("Kontakt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Krajnji datum.
        /// </summary>
        public static string Krajnji_datum {
            get {
                return ResourceManager.GetString("Krajnji_datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj novi.
        /// </summary>
        public static string Kreiraj_novi {
            get {
                return ResourceManager.GetString("Kreiraj_novi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login podaci su netačni!.
        /// </summary>
        public static string Login_podaci_su_netačni_ {
            get {
                return ResourceManager.GetString("Login_podaci_su_netačni_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesečna naknada.
        /// </summary>
        public static string Mesecna_Naknada {
            get {
                return ResourceManager.GetString("Mesecna_Naknada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadimak korisnika.
        /// </summary>
        public static string Nadimak_korisnika {
            get {
                return ResourceManager.GetString("Nadimak_korisnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naplaćeno.
        /// </summary>
        public static string Naplaćeno {
            get {
                return ResourceManager.GetString("Naplaćeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naplaćeno delimično.
        /// </summary>
        public static string Naplaćeno_delimično {
            get {
                return ResourceManager.GetString("Naplaćeno_delimično", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naplaćivanje rate.
        /// </summary>
        public static string Naplacivanje_Rate {
            get {
                return ResourceManager.GetString("Naplacivanje_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavljena saradnja.
        /// </summary>
        public static string Nastavljena_saradnja {
            get {
                return ResourceManager.GetString("Nastavljena_saradnja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazad na listu.
        /// </summary>
        public static string Nazad_na_listu {
            get {
                return ResourceManager.GetString("Nazad_na_listu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        public static string Ne {
            get {
                return ResourceManager.GetString("Ne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne mogu se menjati unosi drugog korisnika!.
        /// </summary>
        public static string Ne_mogu_se_menjati_unosi_drugog_korisnika_ {
            get {
                return ResourceManager.GetString("Ne_mogu_se_menjati_unosi_drugog_korisnika_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne može se brisati unos drugog korisnika.
        /// </summary>
        public static string Ne_može_se_brisati_unos_drugog_korisnika {
            get {
                return ResourceManager.GetString("Ne_može_se_brisati_unos_drugog_korisnika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije plaćeno.
        /// </summary>
        public static string Nije_plaćeno {
            get {
                return ResourceManager.GetString("Nije_plaćeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste ulogovani.
        /// </summary>
        public static string Niste_ulogovani {
            get {
                return ResourceManager.GetString("Niste_ulogovani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obriši.
        /// </summary>
        public static string Obriši {
            get {
                return ResourceManager.GetString("Obriši", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis firme.
        /// </summary>
        public static string Opis_firme {
            get {
                return ResourceManager.GetString("Opis_firme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauzirana saradnja.
        /// </summary>
        public static string Pauzirana_saradnja {
            get {
                return ResourceManager.GetString("Pauzirana_saradnja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string PDF {
            get {
                return ResourceManager.GetString("PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf - Izlaz.
        /// </summary>
        public static string Pdf___Izlaz {
            get {
                return ResourceManager.GetString("Pdf___Izlaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pdf - Ulaz.
        /// </summary>
        public static string Pdf___Ulaz {
            get {
                return ResourceManager.GetString("Pdf___Ulaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početak naplate.
        /// </summary>
        public static string Početak_Naplate {
            get {
                return ResourceManager.GetString("Početak_Naplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Početni datum.
        /// </summary>
        public static string Početni_datum {
            get {
                return ResourceManager.GetString("Početni_datum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pošalji opomenu.
        /// </summary>
        public static string PosaljiOpomenu {
            get {
                return ResourceManager.GetString("PosaljiOpomenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poslata opomena.
        /// </summary>
        public static string Poslata_opomena {
            get {
                return ResourceManager.GetString("Poslata_opomena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potpisan ugovor.
        /// </summary>
        public static string Potpisan_ugovor {
            get {
                return ResourceManager.GetString("Potpisan_ugovor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potrebna konverzija.
        /// </summary>
        public static string Potrebna_konverzija {
            get {
                return ResourceManager.GetString("Potrebna_konverzija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poziv na broj.
        /// </summary>
        public static string Poziv_na_broj {
            get {
                return ResourceManager.GetString("Poziv_na_broj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled.
        /// </summary>
        public static string Pregled {
            get {
                return ResourceManager.GetString("Pregled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeni filter.
        /// </summary>
        public static string Primeni_filter {
            get {
                return ResourceManager.GetString("Primeni_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priprema za produkciju.
        /// </summary>
        public static string Priprema_za_produkciju {
            get {
                return ResourceManager.GetString("Priprema_za_produkciju", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priprema za test.
        /// </summary>
        public static string Priprema_za_test {
            get {
                return ResourceManager.GetString("Priprema_za_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produkcija.
        /// </summary>
        public static string Produkcija {
            get {
                return ResourceManager.GetString("Produkcija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prvi kontakt.
        /// </summary>
        public static string Prvi_kontakt {
            get {
                return ResourceManager.GetString("Prvi_kontakt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raskid ugovora.
        /// </summary>
        public static string Raskid_ugovora {
            get {
                return ResourceManager.GetString("Raskid_ugovora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rata.
        /// </summary>
        public static string Rata {
            get {
                return ResourceManager.GetString("Rata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razno (pogledati komentar).
        /// </summary>
        public static string Razno__pogledati_komentar_ {
            get {
                return ResourceManager.GetString("Razno__pogledati_komentar_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sačuvaj.
        /// </summary>
        public static string Sačuvaj {
            get {
                return ResourceManager.GetString("Sačuvaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo.
        /// </summary>
        public static string Saldo {
            get {
                return ResourceManager.GetString("Saldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo datum.
        /// </summary>
        public static string SaldoDatum {
            get {
                return ResourceManager.GetString("SaldoDatum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stornirano.
        /// </summary>
        public static string Stornirano {
            get {
                return ResourceManager.GetString("Stornirano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testiranje.
        /// </summary>
        public static string Testiranje {
            get {
                return ResourceManager.GetString("Testiranje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip transakcije.
        /// </summary>
        public static string Tip_transakcije {
            get {
                return ResourceManager.GetString("Tip_transakcije", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transakcija.
        /// </summary>
        public static string Transakcija {
            get {
                return ResourceManager.GetString("Transakcija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulaz.
        /// </summary>
        public static string Ulaz {
            get {
                return ResourceManager.GetString("Ulaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vreme unosa.
        /// </summary>
        public static string Vreme_unosa {
            get {
                return ResourceManager.GetString("Vreme_unosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML.
        /// </summary>
        public static string XML {
            get {
                return ResourceManager.GetString("XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml - Izlaz.
        /// </summary>
        public static string Xml___Izlaz {
            get {
                return ResourceManager.GetString("Xml___Izlaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml - Ulaz.
        /// </summary>
        public static string Xml___Ulaz {
            get {
                return ResourceManager.GetString("Xml___Ulaz", resourceCulture);
            }
        }
    }
}
